Stopwatch
aslanovr/TaskManagement pull request #3
Opened 2018-09-20 15:31 UTC by aslanovr

2018-09-20 17:22 UTC, zor07 requested changes
Ну в целом пофиксить все что сказал нужно

2018-09-20 17:22 UTC, zor07 commented on src/main/java/com/rasl/configuration/SecurityConfiguration.java
> +                .antMatchers( "/css/**", "/js/**","/register", "/login/**", "/checkStrength").permitAll()
Эти доработки не относятся к текущей задачи. Старайся не мешать в одной ветке доработки по разным задачам

2018-09-20 17:22 UTC, zor07 commented on src/main/java/com/rasl/controller/MainController.java
> +import org.springframework.http.HttpStatus;
Мне кажется, или тут лишние импорты?

2018-09-23 13:56 UTC, aslanovr commented on src/main/java/com/rasl/controller/MainController.java
> +import org.springframework.http.HttpStatus;
Убрал лишние импорты

2018-09-23 13:56 UTC, aslanovr commented on src/main/java/com/rasl/configuration/SecurityConfiguration.java
> +                .antMatchers( "/css/**", "/js/**","/register", "/login/**", "/checkStrength").permitAll()
Принято

2018-09-23 13:59 UTC, merged